name: 功能请求
description: 为这个项目提出一个想法
title: "features: "
labels: [enhancement]
body:
  - type: input
    id: describe
    attributes:
      label: 您的功能请求是否与问题有关？请描述。
      placeholder: 对问题所在的清晰简洁的描述。当 [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 描述您想要的解决方案
      placeholder: 清晰简洁地描述您想要发生的事情。
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: 描述您考虑过的替代方案 
      description: 对您考虑过的任何替代解决方案或功能进行清晰简洁的描述。
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 附加上下文
      description: 在此处添加有关功能请求的任何其他上下文或屏幕截图。
    validations:
      required: true
