name: CI-Packing-linux64
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.7.5
        cache: pip
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./requirements.txt
    - name: Run packing
      run: |
        pyinstaller ./main.spec
    - name: Run artifact
      run: |
        mkdir OlivOS-PKG
        cp ./dist/main ./OlivOS-PKG/OlivOS
    - name: Packing OlivOS-PKG
      uses: actions/upload-artifact@v2
      with:
        name: OlivOS-Linux-64
        path: ./OlivOS-PKG
