name: CI-Packing-all
on:
  push:
    branches: [ dev-nuitka ]
jobs:
  build-win64-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7.5
        cache: pip
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./requirements_win.txt
        python -m pip install nuitka
    - name: Run packing
      run: |
        cp ./OlivOS/hook.py ./OlivOS/hook_bak.py
        cp ./OlivOS/hook_pack.py ./OlivOS/hook.py
        nuitka --mingw64 --standalone --show-progress --show-memory --enable-plugin=pyqt5 --follow-import-to=need --output-dir=out main.py
    - name: Packing
      uses: actions/upload-artifact@v3
      with:
        name: All
        path: ./
