name: PypiPublish
on:
  push:
    branches: [ pypipublish ]
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  tests:
    needs: lint
    uses: ./.github/workflows/test.yml

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Deploy Pypi
        uses: remorses/pypi@v3
        with:
          setup_file: ./setup.py
          username: __token__
          password: ${{ secrets.OWNERPYPITOKEN }}
