name: CI-Packing-win32
on:
  push:
    branches: [ main, pypyDev ]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Download Pypy
        run: |
          curl -L https://downloads.python.org/pypy/pypy3.8-v7.3.9-win64.zip -o ./pypy.zip
          Expand-Archive ./pypy.zip ./pypy
