name: CI-Packing-Pypy-win32
on:
  push:
    branches: [ main, pypyDev ]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Pypy Prepare
        run: |
          md cache
          curl -L https://downloads.python.org/pypy/pypy3.8-v7.3.9-win64.zip -o ./cache/pypy.zip
          Expand-Archive ./cache/pypy.zip ./cache/pypy
          move ./cache/pypy/pypy3.8-v7.3.9-win64/ ./
          ren ./pypy3.8-v7.3.9-win64 ./pypy
          curl -L https://download.lfd.uci.edu/pythonlibs/archived/Pillow-9.1.1-pp38-pypy38_pp73-win_amd64.whl -o ./cache/Pillow-9.1.1-pp38-pypy38_pp73-win_amd64.whl
          curl -L https://download.lfd.uci.edu/pythonlibs/archived/lxml-4.9.0-pp38-pypy38_pp73-win_amd64.whl -o ./cache/lxml-4.9.0-pp38-pypy38_pp73-win_amd64.whl
      - name: Pypy Install
        run: |
          ./pypy/pypy.exe -m ensurepip
          ./pypy/pypy.exe -m pip install pyinstaller==3.5
          ./pypy/pypy.exe -m pip install flask
          ./pypy/pypy.exe -m pip install gevent
          ./pypy/pypy.exe -m pip install psutil
          ./pypy/pypy.exe -m pip install requests==2.23.0
          ./pypy/pypy.exe -m pip install pybase64
          ./pypy/pypy.exe -m pip install websockets
          ./pypy/pypy.exe -m pip install websocket-client
          ./pypy/pypy.exe -m pip install .\cache\Pillow-9.1.1-pp38-pypy38_pp73-win_amd64.whl
          #./pypy/pypy.exe -m pip install .\cache\lxml.whl#egg=lxml-cffi
          ./pypy/pypy.exe -m pip install -e git+https://github.com/lunzhiPenxil/lxml
          ./pypy/pypy.exe -m pip install rsa
          ./pypy/pypy.exe -m pip install requests_toolbelt
          ./pypy/pypy.exe -m pip install pystray
      - name: Pypy Pack
        run: |
          md release
          md release/OlivOS
          move ./pypy/ ./release/OlivOS
          move ./OlivOS/ ./release/OlivOS
          move ./script/pypystart_publish.bat ./release/OlivOS/OlivOS.bat
          move ./main.py ./release/OlivOS/main.py
      - name: Packing OlivOS-Win-Pypy
        uses: actions/upload-artifact@v2
        with:
          name: OlivOS-Win-Pypy
          path: ./release/OlivOS
          
